name: Github Pages

on:
  push:
    branches:
      - master
      - feature/pages
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install doxygen
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Generate
        run: doxygen docs/Doxyfile
        shell: bash

      - name: Publish docs
        uses: mattnotmitt/doxygen-action@v1.9.5
