name: Build docs and publish to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'docs/Doxyfile'

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
